# tester
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'

module TestComponent
  # Employee Model.
  class Employee < Person
    # Represents a model field
    # @return [String]
    attr_accessor :department

    # Represents a model field
    # @return [List of Person]
    attr_accessor :dependents

    # Represents a model field
    # @return [DateTime]
    attr_accessor :hired_at

    # Represents a model field
    # @return [Days]
    attr_accessor :joining_day

    # Represents a model field
    # @return [Integer]
    attr_accessor :salary

    # Represents a model field
    # @return [List of Days]
    attr_accessor :working_days

    # Represents a model field
    # @return [Person]
    attr_accessor :boss

    # Discriminators mapping.
    def self.discriminators
      if @_discriminators.nil?
        @_discriminators = {}
        @_discriminators['Boss'] = Boss
      end
      @_discriminators
    end

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['department'] = 'department'
      @_hash['dependents'] = 'dependents'
      @_hash['hired_at'] = 'hiredAt'
      @_hash['joining_day'] = 'joiningDay'
      @_hash['salary'] = 'salary'
      @_hash['working_days'] = 'workingDays'
      @_hash['boss'] = 'boss'
      @_hash = super().merge(@_hash)
      @_hash
    end

    # An array for optional fields
    def self.optionals
      _arr = []
      (_arr << super()).flatten!
    end

    # An array for nullable fields
    def self.nullables
      _arr = %w[
        boss
      ]
      (_arr << super()).flatten!
    end

    def initialize(address = nil,
                   age = nil,
                   birthday = nil,
                   birthtime = nil,
                   boss = nil,
                   department = nil,
                   dependents = nil,
                   hired_at = nil,
                   joining_day = Days::MONDAY,
                   name = nil,
                   salary = nil,
                   uid = nil,
                   working_days = nil,
                   person_type = 'Empl',
                   additional_properties = {})
      @department = department
      @dependents = dependents
      @hired_at = hired_at
      @joining_day = joining_day
      @salary = salary
      @working_days = working_days
      @boss = boss

      # Add additional model properties to the instance.
      additional_properties.each do |_name, _value|
        instance_variable_set("@#{_name}", _value)
      end

      # Call the constructor of the base class
      super(address,
            age,
            birthday,
            birthtime,
            name,
            uid,
            person_type)
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Delegate unboxing to another function if a discriminator
      # value for a child class is present.
      unboxer = discriminators[hash['personType']]
      return unboxer.send(:from_hash, hash) if unboxer

      # Extract variables from the hash.
      address = hash.key?('address') ? hash['address'] : nil
      age = hash.key?('age') ? hash['age'] : nil
      birthday = hash.key?('birthday') ? hash['birthday'] : nil
      birthtime = if hash.key?('birthtime')
                    (DateTimeHelper.from_rfc3339(hash['birthtime']) if hash['birthtime'])
                  end
      boss = Person.from_hash(hash['boss']) if hash['boss']
      department = hash.key?('department') ? hash['department'] : nil
      # Parameter is an array, so we need to iterate through it
      dependents = nil
      unless hash['dependents'].nil?
        dependents = []
        hash['dependents'].each do |structure|
          dependents << (Person.from_hash(structure) if structure)
        end
      end

      dependents = nil unless hash.key?('dependents')
      hired_at = if hash.key?('hiredAt')
                   (DateTimeHelper.from_rfc1123(hash['hiredAt']) if hash['hiredAt'])
                 end
      joining_day = hash['joiningDay'] ||= Days::MONDAY
      name = hash.key?('name') ? hash['name'] : nil
      salary = hash.key?('salary') ? hash['salary'] : nil
      uid = hash.key?('uid') ? hash['uid'] : nil
      working_days = hash.key?('workingDays') ? hash['workingDays'] : nil
      person_type = hash['personType'] ||= 'Empl'

      # Clean out expected properties from Hash.
      names.each_value { |k| hash.delete(k) }

      # Create object from extracted values.
      Employee.new(address,
                   age,
                   birthday,
                   birthtime,
                   boss,
                   department,
                   dependents,
                   hired_at,
                   joining_day,
                   name,
                   salary,
                   uid,
                   working_days,
                   person_type,
                   hash)
    end

    def to_hired_at
      DateTimeHelper.to_rfc1123(hired_at)
    end
  end
end
