# type_combinator_simple
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module TestComponent
  # Vehicle Model.
  class Vehicle < TestComponent::BaseModelTypeComb
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :number_of_tyres

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['number_of_tyres'] = 'NumberOfTyres'
      @_hash
    end

    # A mapping from model property names to types.
    def self.types
      @_types = {} if @_types.nil?
      @_types['number_of_tyres'] = 'String'
      @_types
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(number_of_tyres = nil)
      @number_of_tyres = number_of_tyres
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      names.each do |key, value|
        has_default_value = false
        if !((hash.key? value) || (optionals.include? key)) && !has_default_value
          raise ArgumentError,
                "#{value} is not present in the provided hash"
        end
      end

      # Extract variables from the hash.
      number_of_tyres = hash.key?('NumberOfTyres') ? hash['NumberOfTyres'] : nil

      # Create object from extracted values.
      Vehicle.new(number_of_tyres)
    end
  end
end
