# type_combinator_simple
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module CoreLibrary
  # Class for exceptions when there is a schema validation error.
  class ValidationException < StandardError
  end
end
